vega4_head_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_joint
    joint_speed: 0.75
    motor:
        id: 1
        init: 200
        min: 115
        max: 630
vega4_scara_shoulder_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: scara_shoulder_joint
    joint_speed: 0.5
    motor:
        id: 2
        init: 500
        min: 163
        max: 869
vega4_scara_elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: scara_elbow_joint
    joint_speed: 0.5
    motor:
        id: 4
        init: 2015
        min: 188
        max: 3841
vega4_scara_gripper_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: scara_gripper_joint
    joint_speed: 0.5
    motor:
        id: 3
        init: 550
        min: 550
        max: 880
vega4_gantry_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: gantry_joint
    joint_speed: 5
    motor:
        id: 0
        init: 0
        min: 0
        max: 4095
